# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField(null=True)),
                ('comment', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isavailable', models.BooleanField()),
            ],
            options={
                'ordering': ('-productid',),
            },
        ),
    ]
