# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('personId', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('address', models.TextField()),
                ('homePhone', models.TextField()),
                ('cellPhone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('recordIdse', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('buyDate', models.DateTimeField()),
                ('customerId', models.PositiveIntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
